name: Linux ARM (Docker)

on:
  push:
    branches:
      - main

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.2.0

      - uses: docker/setup-buildx-action@v1
        with:
          install: true

      - uses: docker/setup-qemu-action@v1
          
      - name: Build with Docker
        run: |
          # Override OBS version in Dockerfile
          docker build \
            -t obs-linux-arm:latest \
            --output=type=docker \
            --platform=linux/arm64 \
            ./docker
      - name: Extract build files from Docker instance
        run: |
          docker create -ti --name obs-linux-arm-tmp obs-linux-arm bash
          docker cp obs-linux-arm-tmp:/build .
          # docker cp obs-linux-arm-tmp:/scrcpy-server .

      - uses: actions/upload-artifact@v2
        with:
          name: builds
          path: build
          
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: servers
      #     path: scrcpy-server
          